name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:     
  build_apk:
      name: Build Flutter (Android)
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: subosito/flutter-action@v1
        with:
            flutter-version: '3.7.7'
            channel: 'stable'
      - run: flutter clean
        working-directory: ./study_ci_cd
      - run: flutter pub get
        working-directory: ./study_ci_cd
      - run: flutter test
        working-directory: ./study_ci_cd
      - run: flutter build apk --debug
        working-directory: ./study_ci_cd
      - name: Upload APK
        uses: actions/upload-artifact@master
        with:
          name: android-build
          path: ./study_ci_cd/build/app/outputs/apk/debug/*.apk
   
  delete_android_artifact:
    needs: [build_apk]
    name: Delete artifact
    runs-on: ubuntu-latest
    steps:
    - uses: geekyeggo/delete-artifact@v1
      with:
        name: android-build
